In [29]:
#PROBLEM LIST
#Converting time strings to time delta and date time 
#Finding substrings to find entire shows not just a specific episode.

In [40]:
import pandas as pd

In [41]:
file = pd.read_csv('ViewingActivity-sample.csv')

In [42]:
file = file.drop(['Profile Name', 'Attributes', 'Supplemental Video Type', 'Device Type', 'Bookmark', 'Latest Bookmark', 'Country'], axis=1)
#Dropping columns that are not important to our data---<file var>.drop([list of desired dropped columns],axis=1) axis = 1 tells pandas to drop that column.

In [43]:
file #currently the start time and duration (type) == object meaning they are strings. To analyze the data we need 
######to convert the time to Datetime and Timedelta in Pandas
######Cant work with times as a string
######Step 1: Convert Startime from an Object to Datetime so Pandas can perform calculations
######Step 2: Start time will be in UTC time zone so we have to change it to my local time zone EST
######Step 3: Convert Duration to time Delta so Pandas can perform calculations

,Start Time,Duration,Title
0,2013-03-20 5:17:53,0:00:05,Star Trek: Deep Space Nine: Season 5: Empok No...
1,2013-03-20 4:27:45,0:44:31,Star Trek: Deep Space Nine: Season 5: Blaze of...
2,2013-03-20 4:05:21,0:22:06,Star Trek: Deep Space Nine: Season 5: Children...
3,2013-03-20 0:20:03,0:48:14,The Invisible War
4,2013-03-20 0:10:31,0:04:51,The Invisible War
...,...,...,...
195,2013-03-02 0:45:12,0:05:18,Star Trek: Deep Space Nine: Season 4: Body Par...
196,2013-03-01 23:46:16,0:58:12,Louis C.K.: Live at the Beacon Theater
197,2013-03-01 23:21:19,0:21:59,Star Trek: Deep Space Nine: Season 4: Body Par...
198,2013-03-01 22:36:48,0:44:26,Star Trek: Deep Space Nine: Season 4: The Quic...
199,2013-03-01 20:47:09,0:43:48,Star Trek: Deep Space Nine: Season 4: To the D...

In [44]:
#Step 1
file['Start Time'] = pd.to_datetime(file['Start Time'], utc=True)
#used pd.to_datetime()
#UTC is for the time zone identification, started with UTC so we can convert to EST which is done with...
#.tz_convert() catch is that tz.convert can only be used with a Datetimeindex so Start Time first has
#to be set as the index usingn set_index() then we will undo using. reset_index()

In [45]:
file = file.set_index('Start Time')

In [46]:
file.index = file.index.tz_convert('US/Eastern')

In [47]:
file =  file.reset_index()

In [48]:
#file = file.set_index('Start Time')
#file.index = file.index.tz_convert('US/Eastern')
#file = file.reset_index()
file #we are now in eastern time zone and in datetime format
#next is to deal with the duration column

,Start Time,Duration,Title
0,2013-03-20 01:17:53-04:00,0:00:05,Star Trek: Deep Space Nine: Season 5: Empok No...
1,2013-03-20 00:27:45-04:00,0:44:31,Star Trek: Deep Space Nine: Season 5: Blaze of...
2,2013-03-20 00:05:21-04:00,0:22:06,Star Trek: Deep Space Nine: Season 5: Children...
3,2013-03-19 20:20:03-04:00,0:48:14,The Invisible War
4,2013-03-19 20:10:31-04:00,0:04:51,The Invisible War
...,...,...,...
195,2013-03-01 19:45:12-05:00,0:05:18,Star Trek: Deep Space Nine: Season 4: Body Par...
196,2013-03-01 18:46:16-05:00,0:58:12,Louis C.K.: Live at the Beacon Theater
197,2013-03-01 18:21:19-05:00,0:21:59,Star Trek: Deep Space Nine: Season 4: Body Par...
198,2013-03-01 17:36:48-05:00,0:44:26,Star Trek: Deep Space Nine: Season 4: The Quic...
199,2013-03-01 15:47:09-05:00,0:43:48,Star Trek: Deep Space Nine: Season 4: To the D...

In [52]:
#duration column
file['Duration'] = pd.to_timedelta(file['Duration'])